extra_css:
  - css/fix-cinder-sidebar-scrolling.css
nav:
    - InspIRCd 2:
        - Installation: /2/installation
        - Configuration: /2/configuration
        - Commands: /2/commands
        - Modes: /2/modes
        - Modules: /2/modules
        - SNOMasks: /2/snomasks
    - InspIRCd 3:
        - Installation: /3/installation
        - Configuration: /3/configuration
        - Commands: /3/commands
        - Modes: /3/modes
        - Modules: /3/modules
        - SNOMasks: /3/snomasks
    - Downloads: https://github.com/inspircd/inspircd/releases/latest
    - Issue Tracker: https://github.com/inspircd/inspircd/issues
    - Developer API: https://www.inspircd.org/api/
markdown_extensions:
    - extra
    - markdown_include.include:
          base_path: docs
plugins:
  - exclude:
      glob:
        - _*
  - search
copyright: All documentation is licensed under the <a href="/license">GNU GPLv2</a>.
repo_url: https://github.com/inspircd/inspircd-docs
site_description: InspIRCd is a modular C++ Internet Relay Chat (IRC) server for UNIX-like and Windows systems.
site_name: InspIRCd Documentation
theme: cinder
